### ISSUE TITLE
Didn't work for restream.io

### ISSUE THREAD

**Issue by toshi0383** [openfresh/VideoCast-Swift#2]
I tried to stream to https://restream.io but didn't work. (I didn't get any errors but the video appeared all black on Periscope. On YouTube the live stream didn't even start.)
Gonna debug this issue later but submitted this for now.
restream.io currently only supports rtmp.

**Comment by toshi0383** [comment]
Using an app called `Wirecast Go` on iOS, it worked via restream.io to YouTube. Still the same situation with Periscope though.🙄

**Comment by thmatuza** [comment]
You may have used HEVC which RTMP doesn't support.
If so, could you use this line instead of line 19?
https://github.com/openfresh/VideoCast-Swift/blob/master/Example/iOS%20Example/Source/ViewController.swift#L17

HEVC is for SRT.

**Comment by toshi0383** [comment]
Thanks, it worked👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
