### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by CasperMok** [openfresh/VideoCast-Swift#25]
In the project page, it says this is under MIT license. However, a lot of source files have the copyright lines, such as following in VCSimpleSession.swift

`//  Created by Tomohiro Matsuzawa on 2018/01/05.`
`//  Copyright © 2018年 CyberAgent, Inc. All rights reserved.`

May I confirm this whole project can be used under MIT license?

Thanks

**Comment by thmatuza** [comment]
Yes, whole project can be used under MIT license!

**Comment by CasperMok** [comment]
Thank you so much
