### ISSUE TITLE
RTMP H.264 Low Quality Problem

### ISSUE THREAD

**Issue by bablet** [openfresh/VideoCast-Swift#28]
I have been trying to stream to an RTMP server with h.264 encoding but I am unable to get a good quality on the stream. The quality is probably equivalent to a stream with the bitrate set to something to low. I have been trying to debug in VTEncode and also tried different settings on the VTCompressionSession and AVCaptureSession but with no noticeable difference in quality. I do not know if I am missing something in the setup or if this is currently a problem within the framework.

My basic setup

```
    private func initSession() {
        session = VCSimpleSession(
            videoSize: CGSize(width: 1280, height: 720),
            frameRate: 30,
            bitrate: 2000,
            videoCodecType: VCVideoCodecType.h264,
            useInterfaceOrientation: true,
            aspectMode: .fill
        )
        session.useAdaptiveBitrate = false
        session.autoreconnect = true
        previewView.addSubview(session.previewView)
        session.previewView.frame = previewView.bounds
    }

```

**Comment by thmatuza** [comment]
Hi bablet,
The unit of the bitrate parameter is not kbps but bps.
Please use 2000000 instead of 2000.

**Comment by bablet** [comment]
Thank you, Solved the problem!
