### ISSUE TITLE
Audio with a lot of noise

### ISSUE THREAD

**Issue by toshi0383** [openfresh/VideoCast-Swift#4]
Audio has a lot of noise. Why is this?
https://www.youtube.com/watch?v=4O8g1HMP4rU

**Comment by thmatuza** [comment]
It is probably related to sampling rate issues.
FLV have only 5.5kHz, 11kHz, 22kHz and 44kHz in AudioTagHeader, so original library only supported 22kHz and 44kHz.
However, iPhone6S and newer support only 48kHz.

FLV AudioTagHeader is ignored according to this, so RTMP can actually support 48kHz.
https://patchwork.ffmpeg.org/patch/746/

I will fix it.

**Comment by thmatuza** [comment]
I fixed it.

**Comment by toshi0383** [comment]
Beautiful!🙌
